version: "3"

services:
  app:
    image: app
    build: ./
    container_name: app
    volumes:
      - ".:/app"
    ports:
      - 8002:8002
    environment:
      - MEDEX_API_URL=http://host.docker.internal:8000/api
      - NUMAN_API_URL=http://host.docker.internal:3000/v1
